name: Crypto Volatility Alerts

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

env:
  CRON_INTERVAL_MINUTES: 15

jobs:
  run-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run alert script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          THRESHOLD: ${{ vars.THRESHOLD || '5' }}
          TIME_INTERVAL_BETWEEN_VOLATALITY_CHECKS: ${{ vars.TIME_INTERVAL_BETWEEN_VOLATALITY_CHECKS || '30' }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
        run: python crypto-volatality.py
