name: Crypto Volatility Alerts

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

env:
  CRON_INTERVAL_MINUTES: 15

jobs:
  run-alert:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run alert script
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          THRESHOLD: ${{ vars.THRESHOLD || '5' }}
          TIME_INTERVAL_BETWEEN_VOLATALITY_CHECKS: ${{ vars.TIME_INTERVAL_BETWEEN_VOLATALITY_CHECKS || '30' }}
        run: python crypto-volatality.py
      - name: Commit price history
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add prev_prices.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update price history [skip ci]"
          git push
